apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tackles.tackle.io
spec:
  group: tackle.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dockerhubConfigJson:
                  description: 'Tackle uses some images from Dockerhub. To avoid anonymous pulling of those images (and prevent Dockerhub''s pull rate limit), the Docker credentials can be provided using this input field. The value has to be the Base64 encode of the ''config.json'' file. (ref. https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)'
                  type: string
  scope: Namespaced
  names:
    plural: tackles
    singular: tackle
    kind: Tackle
    shortNames:
      - ta
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloaks.tackle.io
spec:
  group: tackle.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                restImage:
                  description: URL for the Rest image
                  type: string
                postgreSQLImage:
                  description: URL for the PostgreSQL image
                  type: string
  scope: Namespaced
  names:
    plural: keycloaks
    singular: keycloak
    kind: Keycloak
    shortNames:
      - kc
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uis.tackle.io
spec:
  group: tackle.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
  scope: Namespaced
  names:
    plural: uis
    singular: ui
    kind: Ui
    shortNames:
      - ui
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: microservices.tackle.io
spec:
  group: tackle.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                restImage:
                  description: URL for the Rest image
                  type: string
                postgreSQLImage:
                  description: URL for the PostgreSQL image
                  type: string
  scope: Namespaced
  names:
    plural: microservices
    singular: microservice
    kind: Microservice
    shortNames:
      - ms
