apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloaks.tackle.io
spec:
  group: tackle.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                restImage:
                  description: URL for the Rest image
                  type: string
                postgreSQLImage:
                  description: URL for the PostgreSQL image
                  type: string
  scope: Namespaced
  names:
    plural: keycloaks
    singular: keycloak
    kind: Keycloak
    shortNames:
      - kc
