apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: microservices.tackle.io
spec:
  group: tackle.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                restImage:
                  description: URL for the Rest image
                  type: string
                postgreSQLImage:
                  description: URL for the PostgreSQL image
                  type: string
                oidcAuthServerUrl:
                  description: URL for OIDC server
                  type: string
                databaseSchema:
                  description: Name of the databse schema
                  type: string
                contextRoot:
                  description: Name of the REST root path
                  type: string
              required:
                - restImage
                - postgreSQLImage
                - databaseSchema
  scope: Namespaced
  names:
    plural: microservices
    singular: microservice
    kind: Microservice
    shortNames:
      - ms
