apiVersion: tackle.io/v1alpha1
kind: Microservice
metadata:
  name: pathfinder
spec:
  restImage: quay.io/konveyor/tackle-pathfinder:0.0.1-SNAPSHOT-native
  postgreSQLImage: postgres:10.6
  databaseSchema: pathfinder_db
  contextRoot: pathfinder
